apiVersion: v1
kind: ConfigMap
metadata:
  name: fastdds-data-analysis-profile
data:
  profile.xml: |
    <?xml version="1.0" encoding="UTF-8" ?>
    <dds>
      <profiles xmlns="http://www.eprosima.com/XMLSchemas/fastRTPS_Profiles">
        <participant profile_name="data_analysis_intermediate_participant_profile" is_default_profile="true">
          <domainId>0</domainId>
          <rtps>
            <name>data_analysis_intermediate_subscriber</name>
            <builtin>
              <discovery_config>
                <discoveryProtocol>CLIENT</discoveryProtocol>
                <discoveryServersList>
                  <locator>
                    <udpv4>
                      <address>10.106.45.18</address>
                      <port>11811</port>
                    </udpv4>
                  </locator>
                </discoveryServersList>
              </discovery_config>
            </builtin>
            <propertiesPolicy>
              <properties>
                <property><name>dds.sec.auth.plugin</name><value>builtin.PKI-DH</value></property>
                <property><name>dds.sec.access.plugin</name><value>builtin.Access-Permissions</value></property>
                <property><name>dds.sec.crypto.plugin</name><value>builtin.AES-GCM-GMAC</value></property>
                <property><name>dds.sec.auth.builtin.PKI-DH.identity_ca</name><value>file:///certs/identity_ca_cert.pem</value></property>
                <property><name>dds.sec.auth.builtin.PKI-DH.identity_certificate</name><value>file:///certs/aggregation_identity_cert.pem</value></property>
                <property><name>dds.sec.auth.builtin.PKI-DH.private_key</name><value>file:///certs/aggregation_identity_key.pem</value></property>
                <property><name>dds.sec.access.builtin.Access-Permissions.permissions_ca</name><value>file:///certs/permissions_ca_cert.pem</value></property>
                <property><name>dds.sec.access.builtin.Access-Permissions.governance</name><value>file:///certs/governance.smime</value></property>
                <property><name>dds.sec.access.builtin.Access-Permissions.permissions</name><value>file:///certs/aggregation_permissions.smime</value></property>
                <property><name>dds.sec.crypto.builtin.AES-GCM-GMAC.rtps_protection_kind</name><value>ENCRYPT</value></property>
              </properties>
            </propertiesPolicy>
          </rtps>
        </participant>

        <subscriber profile_name="data_analysis_intermediate_subscriber_profile" is_default_profile="true">
        </subscriber>

        <topic profile_name="data_analysis_intermediate_topic_profile" is_default_profile="true">
          <name>air_quality_raw</name>
          <dataType>AirSample</dataType>
        </topic>

        <data_reader profile_name="data_analysis_intermediate_reader_profile" is_default_profile="true">
          <topic>
            <historyQos>
              <kind>KEEP_LAST</kind>
              <depth>1000</depth>
            </historyQos>
            <resourceLimitsQos>
              <max_samples>2000</max_samples>
              <max_instances>3</max_instances>
              <max_samples_per_instance>1000</max_samples_per_instance>
              <allocated_samples>1000</allocated_samples>
              <extra_samples>50</extra_samples>
            </resourceLimitsQos>
          </topic>
          <qos>
            <durability>
              <kind>TRANSIENT_LOCAL</kind>
            </durability>
            <reliability>
              <kind>RELIABLE</kind>
            </reliability>
          </qos>
        </data_reader>
        <publisher profile_name="data_analysis_publisher_profile" is_default_profile="false">
        </publisher>
 
        <topic profile_name="data_analysis_output_topic_profile" is_default_profile="false">
          <name>air_quality_agg</name>
          <dataType>AirQualityStats</dataType>
        </topic>
 
        <data_writer profile_name="data_analysis_writer_profile" is_default_profile="false">
          <topic>
            <historyQos>
              <kind>KEEP_LAST</kind>
              <depth>1000</depth>
            </historyQos>
            <resourceLimitsQos>
              <max_samples>2000</max_samples>
              <max_instances>1</max_instances>
              <max_samples_per_instance>1000</max_samples_per_instance>
              <allocated_samples>1000</allocated_samples>
              <extra_samples>50</extra_samples>
            </resourceLimitsQos>
          </topic>
          <qos>
            <durability>
              <kind>TRANSIENT_LOCAL</kind>
            </durability>
            <reliability>
              <kind>RELIABLE</kind>
            </reliability>
          </qos>
        </data_writer>
      </profiles>
    </dds>
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: fastdds-data-analysis-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fastdds-data-analysis
  template:
    metadata:
      labels:
        app: fastdds-data-analysis
    spec:
      nodeName: final
      containers:
      - name: fastdds-data-analysis
        image: hhlh1/fastdds-csv-app:latest
        imagePullPolicy: Always
        env:
        - name: FASTDDS_BUILTIN_TRANSPORTS
          value: "UDPv4"
        - name: FASTDDS_STATISTICS
          value: "HISTORY_LATENCY_TOPIC;NETWORK_LATENCY_TOPIC;PUBLICATION_THROUGHPUT_TOPIC;SUBSCRIPTION_THROUGHPUT_TOPIC;RTPS_SENT_TOPIC;RTPS_LOST_TOPIC;HEARTBEAT_COUNT_TOPIC;ACKNACK_COUNT_TOPIC;NACKFRAG_COUNT_TOPIC;GAP_COUNT_TOPIC;DATA_COUNT_TOPIC;RESENT_DATAS_TOPIC;SAMPLE_DATAS_TOPIC;PDP_PACKETS_TOPIC;EDP_PACKETS_TOPIC;DISCOVERY_TOPIC;PHYSICAL_DATA_TOPIC"
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "400m"
        command: ["/bin/bash", "-lc"]
        args:
          - |
            mkdir -p /healthz
            mkdir -p /data
            echo ok > /healthz/ok
            exec stdbuf -oL -eL /app/csv_analysis_aggregator \
              -c /config/profile.xml \
              --gap-csv /data/analysis_aggregator_gaps.csv \
              --node-id analysis-aggregator
        readinessProbe:
          exec:
            command: ["bash","-lc","test -f /healthz/ok"]
          initialDelaySeconds: 1
          periodSeconds: 1
        livenessProbe:
          exec:
            command: ["bash","-c","test -f /healthz/ok"]
          initialDelaySeconds: 1
          periodSeconds: 1
        volumeMounts:
          - name: fastdds-config-vol
            mountPath: /config
          - name: certs-vol
            mountPath: /certs
            readOnly: true
          - name: healthz
            mountPath: /healthz
          - name: aggregator-data
            mountPath: /data
      volumes:
        - name: fastdds-config-vol
          configMap:
            name: fastdds-data-analysis-profile
        - name: certs-vol
          secret:
            secretName: dds-security-certs
        - name: healthz
          emptyDir: {}
        - name: aggregator-data
          hostPath:
            path: /home/hugo/TFM/desarrollo/Monolithic/data
            type: DirectoryOrCreate
